[package]
name = "cw-test-harness"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cw-multi-test = "0.13.4"
cw20-base = { version = "0.13.4", features = ["library"] }
cosmwasm-std = "1.0.0"
schemars = "0.8"
serde = { version = "1.0.125", default-features = false, features = ["derive"] }
anyhow = "1"
cw20 = { version = "0.13" }

# Project imports 

## Terraswap
terraswap-factory = { version = "0.0.0", git = "https://github.com/terraswap/terraswap" }
terraswap-pair = { version = "0.0.0", git = "https://github.com/terraswap/terraswap" }
terraswap-token = { version = "0.0.0", git = "https://github.com/terraswap/terraswap" }

## Astroport
# TODO: use main branch or version
astroport-pair = { version = "1.0.0", git = "https://github.com/astroport-fi/astroport-core.git", branch = "feat/update_main_to_cosmwasm_1.0.0" }
astroport-token = { version = "1.0.0", git = "https://github.com/astroport-fi/astroport-core.git", branch = "feat/update_main_to_cosmwasm_1.0.0" }
astroport-factory = { version = "1.0.0", git = "https://github.com/astroport-fi/astroport-core.git", branch = "feat/update_main_to_cosmwasm_1.0.0" }
astroport = { version = "2.0.0", git = "https://github.com/astroport-fi/astroport-core.git", branch = "feat/update_main_to_cosmwasm_1.0.0" }
