[package]
name = "cw-mock-querier"
version = "0.1.0"
edition = "2021"
description = "One Mock querier to rule them all"

[lib]
# See https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cw-storage-plus = { version = "0.13.4" }
cosmwasm-storage = { version = "1.0.0" }
cosmwasm-std = { version = "1.0.0" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
astroport = { git = "https://github.com/astroport-fi/astroport-core.git", branch = "feat/update_main_to_cosmwasm_1.0.0", version = "2.0.0" }
cw20 = { version = "0.13.4" }
terra-cosmwasm = "2.2"
terraswap = "2.6.1"
thiserror = { version = "1.0.21" }
